### ISSUE TITLE
Make this app translatable

### ISSUE THREAD

**Issue by ghost** [lduboeuf/t-tris#1]
I would like to contribute and translate this app in French.
However, I do not see a po folder.
Would it be possible to make this app translatable?

**Comment by lduboeuf** [comment]
hello, thank you for your proposal, yes it is possible, but this app doesn't rely on ubuntu touch's default internationalization  process.
It uses standard Qt internationalization tools, are you familiar with ?
I have to setup the project first

**Comment by lduboeuf** [comment]
ok, i've just pushed en/fr/de `ts` files in `i18n` directory.
You can use Qt linguist tool if you wish. e.g ` linguist base_fr.ts`

**Comment by ghost** [comment]
Thank you very much! I proposed a pull request for the French translation.

**Comment by lduboeuf** [comment]
hello @Anne017 ,
I've added some new text, Do you wish to translate them ?
If you find some weird english text, feel free to PR them, i'm not so fluent in english :)

**Comment by ghost** [comment]
Hello @lduboeuf, I proposed a translation through PR #3.
Nothing specifically weird in the English text.
